{% set name = "nvitop-exporter" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name|replace("-", "_") }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 857f10d235a266eebe4a14d83d7dd61dda01b8ee63e66b20750d7398045c1834

build:
  noarch: python
  entry_points:
    - nvitop-exporter = nvitop_exporter.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - nvitop ~={{ version }}
    - prometheus_client >=0.4.0
    - python >={{ python_min }}

test:
  imports:
    - nvitop
    - nvitop_exporter
  commands:
    - pip check
    - nvitop-exporter --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/XuehaiPan/nvitop
  summary: Prometheus exporter built on top of `nvitop`.
  dev_url: https://github.com/XuehaiPan/nvitop
  doc_url: https://nvitop.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - XuehaiPan
